version: "3.8"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:$PORT:8080"
    env_file:
      - .env
    networks:
      - webhooker

networks:
  webhooker:
    external:
      name: webhooker
