version: "3.8"
services:
  web:
    build: .
    image: ghcr.io/cfc-servers/cfc_heartbeat_server:latest.
    ports:
      - "$PORT:8080"
    env_file:
      - .env

  networks:
    webhooker:
      external:
        name: webhooker
